version: '3.8'

services:
  datasoup-monitoring:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/root/data
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    restart: unless-stopped
    command: ["./monitoring_server"]

  datasoup-worker:
    build: .
    volumes:
      - ./data:/root/data
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    restart: "no"
    command: ["./main"]
    profiles:
      - worker
